apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: splunk-prod
resources:
  - ../../base
patches:
  - target:
      kind: Namespace
      name: splunk
    patch: |
      - op: replace
        path: /metadata/name
        value: splunk-prod
      - op: add
        path: /metadata/labels/env
        value: prod
  - target:
      kind: Service
      name: splunk
    patch: |
      - op: replace
        path: /spec/ports/0/port
        value: 8091
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8000
