apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: splunk-dev
resources:
  - ../../base
patches:
  - target:
      kind: Namespace
      name: splunk
    patch: |
      - op: replace
        path: /metadata/name
        value: splunk-dev
      - op: add
        path: /metadata/labels/env
        value: dev
  - target:
      kind: Service
      name: splunk
    patch: |
      - op: replace
        path: /spec/ports/0/port
        value: 28091
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8000
  - target:
      kind: StatefulSet
      name: splunk
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
